/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-08-08 00:13:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>\r\n");
      out.write("      iFrame예제\r\n");
      out.write("    </title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <table width='1200px' border='1' bgcolor='#F0F0F0' align='center'style=\"border-collapse: collapse;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<table width='1200px'>\r\n");
      out.write("\t\t\t\t<col width=\"200\">  <col width=\"200\"> <col width=\"200\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td >1 </td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><img src=\"./image/mainlogo.PNG\"> </td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"right\" valign=\"top\"> <a href=\"./index.jsp\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">로그인</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("      <tr bgcolor='#BDDD7D'>\r\n");
      out.write("        <td width='200' align='center'>\r\n");
      out.write("          <a href='doc1.html' target='view'>찾습니다</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td width='200' align='center'>\r\n");
      out.write("          <a href='../save/saveboard.jsp' target='view'>보호중입니다</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td width='200' align='center'>\r\n");
      out.write("          <a href='#' target='view'>알바</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td width='200' align='center'>\r\n");
      out.write("          <a href='../board/freeboard.jsp' target='view'>자유게시판</a>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      \r\n");
      out.write("      <tr>\r\n");
      out.write("      <td colspan=\"4\">\r\n");
      out.write("      \t <table width='100%' align='center'>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t      \t<td width=\"200px\">\r\n");
      out.write("\t      \t\t<img src=\"./image/sidebar.PNG\">\r\n");
      out.write("\t      \t</td>\r\n");
      out.write("\t        <td>\r\n");
      out.write("\t          <iframe width='1000px' height=\"600px\" frameborder='0' scrolling='no' src='main.jsp' \r\n");
      out.write("\t               marginwidth='15px' marginheight='15px' name='view' hspace='0px' vspace='0px' >\r\n");
      out.write("\t               \r\n");
      out.write("\t         </iframe>\r\n");
      out.write("\t         \r\n");
      out.write("\t        </td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t    \t\t<td colspan=\"2\">\r\n");
      out.write("\t    \t\t\t<table width='100%' >\r\n");
      out.write("\t    \t\t\t\t<col width=\"150px\"><col width=\"150px\"><col width=\"350\"><col width=\"150px\">\r\n");
      out.write("\t    \t\t\t\t<tr>\r\n");
      out.write("\t    \t\t\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t    \t\t\t\t\t\t<img src=\"../board/image/line.PNG\" width=\"100%\">\r\n");
      out.write("\t    \t\t\t\t\t</td>\r\n");
      out.write("\t    \t\t\t\t</tr>\r\n");
      out.write("\t    \t\t\t\t<tr> \r\n");
      out.write("\t    \t\t\t\t\t<td> 1</td>\r\n");
      out.write("\t    \t\t\t\t\t<td><img src=\"./image/mainlogo.PNG\" width=\"200px\" height=\"50px\"></td>\r\n");
      out.write("\t    \t\t\t\t\t<td>왜안되니?</td>\r\n");
      out.write("\t    \t\t\t\t\t<td>2 </td>\r\n");
      out.write("\t    \t\t\t\t</tr>\r\n");
      out.write("\t    \t\t\t</table>\r\n");
      out.write("\t    \t\t\t\r\n");
      out.write("\t    \t\t</td>\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t</tr>\r\n");
      out.write("    \r\n");
      out.write("   \t </table>\r\n");
      out.write("   \t </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("    </table>    \r\n");
      out.write("  </body>\t\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
