/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-08-08 15:22:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.10.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<!-- 우편주소 -->\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>회원가입</h1>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<form action=\"regiAf.jsp\" id=\"regiform\" name=\"regiform\">\r\n");
      out.write("\t\t\t<table border=\"1\" margin=\"auto\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"120\">이름</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"name\" id=\"name\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"ex)홍길동\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"120\">아이디</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"id\" id=\"id\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" id=\"id_check\" name=\"id_check\" value=\"아이디 중복체크\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"120\">비밀번호</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"pwd1\" id=\"pwd1\">&nbsp;&nbsp;&nbsp;<font\r\n");
      out.write("\t\t\t\t\t\tcolor=\"red\">6자 이상 입력해 주세요</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"120\">비밀번호 확인</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"pwd2\" id=\"pwd2\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"패스워드\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"120\">핸드폰 번호</td>\r\n");
      out.write("\t\t\t\t\t<td\r\n");
      out.write("\t\t\t\t\t\tonkeypress=\"if (event.keyCode<48|| event.keyCode>57) event.returnValue=false;\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"IME-MODE: disabled;\">\r\n");
      out.write("\t\t\t\t\t\t<select id =\"phone\" name=\"phone\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t</select> - \r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\"\tname=\"phone1\" id=\"phone1\" size=\"5\" maxlength=\"4\"> - \r\n");
      out.write("\t\t\t\t\t\t<input\ttype=\"text\" name=\"phone2\" id=\"phone2\" size=\"5\" maxlength=\"4\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>우편번호</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"addrNum\" name=\"addrNum\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"우편번호\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"><Br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" size=\"40\" id=\"addr1\" name=\"addr1\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"주소\"><Br> <input type=\"text\" size=\"40\"\r\n");
      out.write("\t\t\t\t\t\tid=\"addr2\" name=\"addr2\" placeholder=\"상세주소\"></td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"120\">이메일</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"email\" id=\"email\" width=\"140\"\r\n");
      out.write("\t\t\t\t\t\tsize=\"15\">@ <input type=\"text\" name=\"email2\" id=\"email2\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"140\" size=\"15\" disabled value=\"naver.com\"> \r\n");
      out.write("\t\t\t\t\t\t<select\tid=\"email_select\" name=\"email_select\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"@naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"@daum.com\">daum.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"@gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">직접입력</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>성별</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"gender\" id=\"gender\"onclick=\"genderCheck(this);\" value=\"남\" checked=\"checked\">남 \r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"gender\" id=\"gender\"onclick=\"genderCheck(this);\" value=\"여\">여\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"S_button\" value=\"가입하기\">\r\n");
      out.write("\t\t\t<input type=\"reset\" value=\"취소\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#S_button\").click(function() {\r\n");
      out.write("\t\t\tif ($(\"#name\").val() == \"\") { //이름\r\n");
      out.write("\t\t\t\talert(\"이름 을 입력해주세요\")\r\n");
      out.write("\t\t\t\t$(\"#name\").focus();\r\n");
      out.write("\t\t\t} else if ($(\"#id\").val() == \"\") { //아이디\r\n");
      out.write("\t\t\t\talert(\"id를 입력해주세요\")\r\n");
      out.write("\t\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\t} else if ($(\"#pwd1\").val() == \"\") { //패스워드\r\n");
      out.write("\t\t\t\talert(\"패스워드를 입력해주세요\")\r\n");
      out.write("\t\t\t\t$(\"#pwd1\").focus();\r\n");
      out.write("\t\t\t} else if ($(\"#pwd2\").val() == \"\") { //패스워드 확인\r\n");
      out.write("\t\t\t\talert(\"패스워드 확인을 입력해주세요\")\r\n");
      out.write("\t\t\t\t$(\"#pwd2\").focus();\r\n");
      out.write("\t\t\t} else if ($(\"#email\").val() == \"\") { //이메일 공란\r\n");
      out.write("\t\t\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\t\t\t$(\"#email\").focus();\r\n");
      out.write("\t\t\t} else if ($(\"#pwd1\").val() != $(\"#pwd2\").val()) { //패스워드확인 체크\r\n");
      out.write("\t\t\t\talert(\"패스워드 가 다릅니다 \");\r\n");
      out.write("\t\t\t\t$(\"#pwd1\").focus();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#regiform').attr(\"target\", \"_self\").submit(); //로그인후 submit\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction genderCheck(chk) { //check box 한개만 표시하게 하는 javascript\r\n");
      out.write("\t\t\tvar obj = document.getElementsByName(\"gender\");\r\n");
      out.write("\t\t\tfor (var i = 0; i < obj.length; i++) {\r\n");
      out.write("\t\t\t\tif (obj[i] != chk) {\r\n");
      out.write("\t\t\t\t\tobj[i].checked = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#email_select').change(function(){\r\n");
      out.write("\t\t\t$('#email_select option:selected' ).each(function(){\r\n");
      out.write("\t\t\t\tif($(this).val()=='1'){//집접 입력일경우\r\n");
      out.write("\t\t\t\t\t$('#email2').val('');\r\n");
      out.write("\t\t\t\t\t$('#email2').attr(\"disabled\",false) // 활성화\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$('#email2').val($(this).text());\r\n");
      out.write("\t\t\t\t\t\t$('#email2').attr(\"disabled\",true) // 활성화 \r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction sample6_execDaumPostcode() {\r\n");
      out.write("\t\t\tnew daum.Postcode({\r\n");
      out.write("\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\tvar fullAddr = ''; // 최종 주소 변수\r\n");
      out.write("\t\t\t\t\tvar extraAddr = ''; // 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("\t\t\t\t\tif (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("\t\t\t\t\t\tfullAddr = data.roadAddress;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t} else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("\t\t\t\t\t\tfullAddr = data.jibunAddress;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 사용자가 선택한 주소가 도로명 타입일때 조합한다.\r\n");
      out.write("\t\t\t\t\tif (data.userSelectedType === 'R') {\r\n");
      out.write("\t\t\t\t\t\t//법정동명이 있을 경우 추가한다.\r\n");
      out.write("\t\t\t\t\t\tif (data.bname !== '') {\r\n");
      out.write("\t\t\t\t\t\t\textraAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t// 건물명이 있을 경우 추가한다.\r\n");
      out.write("\t\t\t\t\t\tif (data.buildingName !== '') {\r\n");
      out.write("\t\t\t\t\t\t\textraAddr += (extraAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t// 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.\r\n");
      out.write("\t\t\t\t\t\tfullAddr += (extraAddr !== '' ? ' (' + extraAddr + ')'\r\n");
      out.write("\t\t\t\t\t\t\t\t: '');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('addrNum').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('addr1').value = fullAddr;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('addr2').focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).open();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#id_check\").click(function(){\r\n");
      out.write("\t\t\t\tvar idcheck =false;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\turl:\"idcheck.jsp\",\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\tcheckid:$('#id').val(),\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tif(data.trim() == \"true\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"중복된 ID\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"사용가능 ID\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
